#! /bin/bash

mkdir build & cd build

unset https_proxy
unset http_proxy
unset ftp_proxy
export LC_ALL='en_US.UTF-8'
export LANG=C
export VCS_HOME=/auto/da/cad/synopsys/VCS/vcs_mx_vO-2018.09-SP2_1
export WORKING_DIR=/export/data/verif/bochkareva_s
export LD_LIBRARY_PATH=/export/data/verif/bochkareva_s/build
source /auto/vgr/tools/lmlicenserc.bash
/auto/da/cad/synopsys/VCS/vcs_mx_vO-2018.09-SP2_1/bin/vcs \
			-full64 \
                	../src/test.sv \
			../src/grey.v \
			../src/grey.c \
			-sverilog \
			-cm line -cm cond -cm branch \
			-cm_name cov_grey \
			$@
