#! /bin/bash

unset https_proxy
unset http_proxy
unset ftp_proxy
export LC_ALL='en_US.UTF-8'
export LANG=C
export VCS_HOME=/auto/da/cad/synopsys/VCS/vcs_mx_vO-2018.09-SP2_1
source /auto/vgr/tools/lmlicenserc.bash
/auto/da/cad/synopsys/VCS/vcs_mx_vO-2018.09-SP2_1/bin/vcs $@
